### ISSUE TITLE
Lambda reference genome

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#1]
Is this the correct reference genome for phage lambda?
http://www.ncbi.nlm.nih.gov/nuccore/215104?report=fasta

 Need to download the reference for alignment  (bwa/ last) !

If it is correct, you can copy it from /scratch/beegfs/monthly/aechchik/SIB_Bern16/minion/ref_genome/Lambda.fasta

**Comment by julien-roux** [comment]
Emmanuel had downloaded the genome at: `ftp://ftp.ncbi.nlm.nih.gov/genomes/Viruses/Enterobacteria_phage_lambda_uid14204/NC_001416.fna`
Is this the same? I don't see the IDs to be mathcing (I looked very quickly sorry)

**Comment by aechchiki** [comment]
I'll take Emmanuel's one :) thanks
