### ISSUE TITLE
Lambda fast5

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#2]
I could find Lambda fastq in`/archive/dee/robinson/jroux/MinION/Minion_Lambda_Library`

But where to find the original fast5 files? I tried to: 
-  cd to the path in the fastq header in the fastq (`/data/cig/daf/data1/MINION/LambdaBurnIn/Metrichor/Downloads_burnin/`), bu I got the error: `No such file or directory` (touch?)
- cd to`/archive/cig/daf/`, but I got `Permission denied`

So, if anyone of you has access to cig and/or knows the path to basecalled fast5, please let me know. 

Anyways, I put the fast5 to fastq part in the tutorial, tested on Drosophila dataset :)

**Comment by julien-roux** [comment]
The burn-in raw data from lambda phage are available in 
`/home/jroux/archive/MinION/run_MinION_2015_06_15_Burn-In.tar`
Feel free to copy that to your `/scratch/cluster/`

**Comment by aechchiki** [comment]
nice! thanks
