### ISSUE TITLE
assembly with MinION 

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#3]
For assembly, I tried to follow the tutorial from porecamp (`http://nbviewer.jupyter.org/github/PoreCamp/porecamp.github.io/blob/master/tutorials/Identification%20and%20assembly%20practical.ipynb` ). The are using minimap and miniasm , I think they are pretty interesting for us because this software can deal with both ONT and PacBio (`http://bioinformatics.oxfordjournals.org/content/early/2016/03/18/bioinformatics.btw152.abstract`).

I could follow the commands, but honestly I did not get how it works. 

Examples of code usage on github explain a bit more, but still a bit unclear to me ( `https://github.com/lh3/minimap`and `https://github.com/lh3/miniasm`). I will talk to @KamilSJaron tomorrow and see what he suggests.

**Comment by julien-roux** [comment]
Cool, thanks for this. Indeed it is a good idea to try miniasm first 
since it is also quite fast
Yes it is a good idea to talk to Kamil, he probably has some experience 
with it
What is unclear to you? How to make it work, or what the algo is exactly 
doing?

On 6/8/16 9:34 PM, Amina Echchiki wrote:

> For assembly, I tried to follow the tutorial from porecamp 
> (|http://nbviewer.jupyter.org/github/PoreCamp/porecamp.github.io/blob/master/tutorials/Identification%20and%20assembly%20practical.ipynb| 
> ). The are using minimap and miniasm , I think they are pretty 
> interesting for us because this software can deal with both ONT and 
> PacBio 
> (|http://bioinformatics.oxfordjournals.org/content/early/2016/03/18/bioinformatics.btw152.abstract|).
> 
> Honestly I did not get how it works.
> 
> Examples of code usage on github explain a bit more, but still a bit 
> unclear to me ( |https://github.com/lh3/minimap|and 
> |https://github.com/lh3/miniasm|). I will talk to @KamilSJaron 
> https://github.com/KamilSJaron tomorrow and see what he suggests.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/aechchiki/SIB_LongReadsWorkshop_Bern16/issues/3, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AJ883TzP9p9iKOnHUWk3rsmQ7RKL_u0-ks5qJxktgaJpZM4IxUaQ.

## 

Julien Roux
Department of Ecology and Evolution, University of Lausanne, Switzerland
http://www.unil.ch/dee/home/menuinst/people/post-docs--associates/dr-julien-roux.html
Tel: +41 78 700 2931
Twitter: @_julien_roux

**Comment by aechchiki** [comment]
I think I can make it work, but the algorithm is a bit obscure :)

**Comment by aechchiki** [comment]
ok, so the assembly is done (minimap/miniasm), it is very fast! (done in 3 min)

**Comment by julien-roux** [comment]
Cool, 3 minutes is totally feasible for a practical ;)
