### ISSUE TITLE
software to be installed 

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#4]
Tools on vital-it:
module add UHTS/Analysis/poretools/0.5.1 # (read extraction)
module add UHTS/Aligner/bwa/0.7.13 #  (alignment)
module add UHTS/Analysis/samtools/1.3 #  (alignment)
module add SequenceAnalysis/SequenceAlignment/last/531 #  (alignment)
module add UHTS/Analysis/seqtk/2015.10.15 # fastq to fasta
module add UHTS/Quality_control/quast/4.1 # post-alignment control 

Tools NOT on vital-it (but can be found in my /home/aechchik/bin/):
nanopore scripts (https://github.com/arq5x/nanopore-scripts) - ( post-last alignment )
minimap (https://github.com/lh3/minimap) (assembly)
miniasm (https://github.com/lh3/miniasm) (assembly)

=> need to ask Sébastien to install them on Vital-IT before workshop?

**Comment by julien-roux** [comment]
Yes ask Sebastien (at least for minimap / miniasm)
If too much work from the, put them on your ~/bin/ wiht execution permissions for everyone, this should be fine. I have done that for nanoOK

**Comment by aechchiki** [comment]
ok
