### ISSUE TITLE
directory cleaning

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#5]
to clean the repo, I think we can remove:
- MinION.sh
- MinION_lecture.txt
- MinION_report.pdf
- PacBio.sh
- PacBio_report.pdf

I will proceed once you all agree

**Comment by julien-roux** [comment]
Good idea! You can go ahead

Julien

On 7/4/16 2:00 PM, Amina Echchiki wrote:

> to clean the repo, I think we can remove:
> - MinION.sh
> - MinION_lecture.txt
> - MinION_report.pdf
> - PacBio.sh
> - PacBio_report.pdf
> 
> I will proceed once you all agree
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/aechchiki/SIB_LongReadsWorkshop_Bern16/issues/5, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AJ883fRmEQf2xAtH6-SHhtJRzD_9I3IZks5qSPXQgaJpZM4JETqp.

## 

Julien Roux
Department of Ecology and Evolution, University of Lausanne, Switzerland
http://www.unil.ch/dee/home/menuinst/people/post-docs--associates/dr-julien-roux.html
Tel: +41 78 700 2931
Twitter: @_julien_roux

**Comment by aechchiki** [comment]
alright! :)
