### ISSUE TITLE
path names

### ISSUE THREAD

**Issue by aechchiki** [aechchiki/SIB_LongReadsWorkshop_Bern16#6]
on cluster, `/scratch/beegfs/monthly/SIB_long_read_workshop` , the reads are in folders: 
- `MinION_lambda_reads` 
- `RSII_lambda_reads`. 

Should I: 
1. rename paths in both practicals.md and /scripts according to the folder name?
OR
2. rename the folder on cluster (and path in scripts) according to the paths given in practicals.md?

**Comment by wgharib** [comment]
Thx Amina, nb 1 is a good option.

On 04/07/16 14:29, Amina Echchiki wrote:

> on cluster, |/scratch/beegfs/monthly/SIB_long_read_workshop| , the 
> reads are in folders:
> - |MinION_lambda_reads|
> - |RSII_lambda_reads|.
> 
> Should I:
> 1. rename paths in both practicals.md and /scripts according to the 
> folder name?
> OR
> 2. rename the folder on cluster (and path in scripts) according to the 
> paths given in practicals.md?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/aechchiki/SIB_LongReadsWorkshop_Bern16/issues/6, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGXVQWc9nJrYH2mJFO-zb_gGu0arNXB6ks5qSPyXgaJpZM4JEU8D.

## 

Gharib Walid, PhD
Swiss Institute of Bioinformatics (SIB)
Biophore, University of Lausanne, 1015 Lausanne, Switzerland
tel: +41 21 692 42 04

**Comment by aechchiki** [comment]
alright! :)
